service: peeranha-query-index

custom:
  stage: ${opt:stage, 'offline'}
  region: ${file(./stages/${self:custom.stage}.yml):region}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
    ignoreJWTSignature: true
  dynamodb:
    stages:
      - offline
    start:
      port: 4659
      inMemory: true
      migrate: true
  serverless-offline-sqs:
    autoCreate: true
    endpoint: http://0.0.0.0:9324
    region: ${self:custom.region}
    accessKeyId: root
    secretAccessKey: root
  elasticmq:
    stages:
      - dev
    start:
      port: 9324
      noStart: false

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs16.x
  environment: ${file(./stages/${self:custom.stage}.yml):environment}
  memorySize: 512
  timeout: 10
  logRetentionInDays: 30
  logs:
    httpApi: true
  httpApi:
    cors: true
  ecr:
    images:
      peeranha-ecs-nodejs:
        path: ./
        file: Dockerfile
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - sqs:SendMessage
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - translate:TranslateText
            - comprehend:DetectDominantLanguage
          Resource: "*"
  vpc:
    securityGroupIds:
      - ${self:provider.environment.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:provider.environment.SUBNET_ID_1}
      - ${self:provider.environment.SUBNET_ID_2}
fargate:
  vpc:
    securityGroupIds:
      - ${self:provider.environment.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:provider.environment.SUBNET_ID_1}
      - ${self:provider.environment.SUBNET_ID_2}
    assignPublicIp: true
  tasks:
    first-sui-events-listener:
      name: ${self:custom.stage}-first-sui-events-listener
      image: peeranha-ecs-nodejs
      command:
        - "./dist/sui-events-listener.mjs"
      environment:
        ENV: ${self:provider.environment.ENV}
        REGION: ${self:provider.environment.REGION}
        SQS_ENDPOINT: ${self:provider.environment.SQS_ENDPOINT}
        AWS_ACCOUNT_ID: ${self:provider.environment.AWS_ACCOUNT_ID}
        DYNAMODB_ENDPOINT: ${self:provider.environment.DYNAMODB_ENDPOINT}
        SUI_PACKAGE_ADDRESS: ${self:provider.environment.SUI_PACKAGE_ADDRESS}
        SUI_USERS_RATING_COLLECTION: ${self:provider.environment.SUI_USERS_RATING_COLLECTION}
    first-edgeware-events-listener:
      name: ${self:custom.stage}-first-edgeware-events-listener
      image: peeranha-ecs-nodejs
      command:
        - "./dist/edgeware-events-listener.mjs"
      environment:
        ENV: ${self:provider.environment.ENV}
        REGION: ${self:provider.environment.REGION}
        SQS_ENDPOINT: ${self:provider.environment.SQS_ENDPOINT}
        AWS_ACCOUNT_ID: ${self:provider.environment.AWS_ACCOUNT_ID}
        DYNAMODB_ENDPOINT: ${self:provider.environment.DYNAMODB_ENDPOINT}
        COMMUNITY_ADDRESS: ${self:provider.environment.COMMUNITY_ADDRESS}
        CONTENT_ADDRESS: ${self:provider.environment.CONTENT_ADDRESS}
        USER_ADDRESS: ${self:provider.environment.USER_ADDRESS}
        TOKEN_ADDRESS: ${self:provider.environment.TOKEN_ADDRESS}
        NFT_ADDRESS: ${self:provider.environment.NFT_ADDRESS}
        EDGEWARE_START_BLOCK_NUMBER: ${self:provider.environment.EDGEWARE_START_BLOCK_NUMBER}
        RPC_EDGEWARE_ENDPOINT: ${self:provider.environment.RPC_EDGEWARE_ENDPOINT}

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - httpApi:
          path: '/graphql'
          method: 'POST'

  # first-period-trigger:
  #   handler: src/handlers/first-period-trigger.handler
  #   timeout: 300
  #   events:
  #     - schedule:
  #         name: first-period-trigger-${self:custom.stage}
  #         rate: rate(10 minutes)

  # second-period-trigger:
  #   handler: src/handlers/second-period-trigger.handler
  #   timeout: 300
  #   events:
  #     - schedule:
  #         name: second-period-trigger-${self:custom.stage}
  #         rate: rate(10 minutes)
  
  # first-polygon-event-listener-webhook:
  #   handler: src/handlers/first-polygon-event-listener-webhook.handler
  #   timeout: 28
  #   events:
  #     - httpApi:
  #         path: '/polygon-event-listener/first-webhook'
  #         method: 'POST'
  
  # second-polygon-event-listener-webhook:
  #   handler: src/handlers/second-polygon-event-listener-webhook.handler
  #   timeout: 28
  #   events:
  #     - httpApi:
  #         path: '/polygon-event-listener/second-webhook'
  #         method: 'POST'

  # first-sui-onchain-events-read:
  #   handler: src/handlers/first-sui-onchain-events-read.handler
  #   timeout: 300
  #   events:
  #     - schedule:
  #         name: first-sui-read-onchain-events-${self:custom.stage}
  #         rate: rate(1 minute)

  first-edgeware-onchain-events-read:
    handler: src/handlers/first-edgeware-onchain-events-read.handler
    timeout: 300
    events:
      - schedule:
          name: first-edgeware-read-onchain-events-${self:custom.stage}
          rate: rate(1 minute)

  # first-indexing-queue:
  #   handler: src/handlers/first-indexing-queue.handler
  #   timeout: 50
  #   events:
  #     - sqs:
  #         arn:
  #           Fn::GetAtt:
  #             - firstQueue
  #             - Arn

  # second-indexing-queue:
  #   handler: src/handlers/second-indexing-queue.handler
  #   timeout: 50
  #   events:
  #     - sqs:
  #         arn:
  #           Fn::GetAtt:
  #             - secondQueue
  #             - Arn
  
  first-edgeware-indexing-queue:
    handler: src/handlers/edgeware-first-indexing-queue.handler
    timeout: 50
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - firstEdgewareQueue
              - Arn
      
  first-sui-indexing-queue:
    handler: src/handlers/sui-first-indexing-queue.handler
    timeout: 50
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - firstSuiQueue
              - Arn

  first-sui-content-queue:
    handler: src/handlers/sui-first-content-queue.handler
    timeout: 50
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - firstSuiContentQueue
              - Arn

resources:
  Resources:
    queryIndexConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-query-index-config
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    firstQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-firstQueue.fifo
        VisibilityTimeout: 50
        FifoQueue: true
        ContentBasedDeduplication: true
        DeduplicationScope: messageGroup
        FifoThroughputLimit: perMessageGroupId

    # secondQueue:
    #   Type: AWS::SQS::Queue
    #   Properties:
    #     QueueName: ${self:custom.stage}-secondQueue.fifo
    #     VisibilityTimeout: 50
    #     FifoQueue: true
    #     ContentBasedDeduplication: true
    #     DeduplicationScope: messageGroup
    #     FifoThroughputLimit: perMessageGroupId

    firstEdgewareQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-firstEdgewareQueue.fifo
        VisibilityTimeout: 50
        FifoQueue: true
        ContentBasedDeduplication: true
        DeduplicationScope: messageGroup
        FifoThroughputLimit: perMessageGroupId

    firstSuiQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-firstSuiQueue.fifo
        VisibilityTimeout: 50
        FifoQueue: true
        ContentBasedDeduplication: true
        DeduplicationScope: messageGroup
        FifoThroughputLimit: perMessageGroupId

    firstSuiContentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-firstSuiContentQueue.fifo
        VisibilityTimeout: 50
        FifoQueue: true
        ContentBasedDeduplication: true
        DeduplicationScope: messageGroup
        FifoThroughputLimit: perMessageGroupId

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline-sqs
  - serverless-offline-elasticmq
  - serverless-fargate