service: peeranha-query-index

custom:
  stage: ${opt:stage, 'offline'}
  region: ${file(./stages/${self:custom.stage}.yml):region}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
    ignoreJWTSignature: true

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs16.x
  environment: ${file(./stages/${self:custom.stage}.yml):environment}
  memorySize: 512
  timeout: 10
  logRetentionInDays: 30
  lambdaHashingVersion: 20201221
  logs:
    httpApi: true
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "*"
  vpc:
    securityGroupIds:
      - ${self:provider.environment.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:provider.environment.SUBNET_ID_1}
      - ${self:provider.environment.SUBNET_ID_2}

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - httpApi:
          path: '/graphql'
          method: 'POST'

  blockchain-db-period-trigger:
    handler: src/handlers/blockchain-db-period-trigger.handler
    timeout: 300
    events:
      - schedule:
          name: blockchain-db-period-trigger-${self:custom.stage}
          rate: rate(5 minutes)    

  indexing-queue:
    handler: src/handlers/indexing-queue.handler
    timeout: 50
    events:
      - sqs: arn:aws:sqs:${self:custom.region}:${self:provider.environment.AWS_ACCOUNT_ID}:${self:provider.environment.QUEUE_NAME}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin