region: 'us-east-2'
environment:
  ENV: 'prod'
  REGION: 'us-east-2'
  AWS_ACCOUNT_ID: '744343761277'

  DB_NAME: 'prod_query_index'

  MAIN_CONTRACT_ADDRESS: '0xD68fD3afA237D0F96493c959fC150bc584b87AE4'
  COMMUNITY_CONTRACT_ADDRESS: '0xB43F43FC6707EC05C995A14dCAA30dDCE344eb22'
  USER_CONTRACT_ADDRESS: '0xc51ABb9835Ac274733c18cFeb9A196717D51F512'
  TOKEN_CONTRACT_ADDRESS: '0x210F56cA5f54B32f116132037a911A073fb17131'
  
  DYNAMODB_ENDPOINT: 'https://dynamodb.us-east-2.amazonaws.com'
  SQS_ENDPOINT: 'https://sqs.us-east-2.amazonaws.com'

  SECURITY_GROUP_ID: 'sg-ee14be82'
  SUBNET_ID_1: 'subnet-57428e1b'
  SUBNET_ID_2: 'subnet-cb7d53a3'

  IPFS_CDN_URL: 'https://ipfs-cdn.testpeeranha.io/'
  RPC_ENDPOINT: 'https://rpc.ankr.com/polygon_mumbai'

  SUI_PACKAGE_ADDRESS: '0xc182e9bc5cb458a0f9af8cede0c95a5b58b0a1692235293d52dd999665bf2e06'
  SUI_USERS_RATING_COLLECTION: '0xa611c836761223a2c22118549d756892072b9fb4bee9329249ff27d242b79560'

